[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["HEAVY.AI", "Brendan Turner", "Chris Matzenbach"]

# The title and description fields are primarily for displaying extension info in UI
title = "Heavy Omni.UI Component System"
description="Component class for UI organization and encapsulation"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "./docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/heavyai/omni-component"

# One of categories for UI.
category = "Rendering"

# Keywords for the extension
keywords = ["heavyai", "component", "react"]

# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "resources/partner-spotlight-slide.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "resources/logo_black.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "heavyai.ui.component"
